### PR TITLE
Fix empty subscription bug

### LINKED ISSUE #14: Empty subscription is erroneously added
When using standalone checks, if the client config JSON doesn't contain any subscriptions and SENSU_CLIENT_SUBSCRIPTIONS is not set (or is empty), then an empty subscription is added, which causes the client to enter an endless loop of errors:

> [N 161122 23:29:05 standalone.go:29] Setup standalone check test_check
> [N 161122 23:29:05 subscriber.go:40] Subscribed to
> [N 161122 23:29:05 client.go:78] Transport disconnected
> [E 161122 23:29:05 rabbitmq.go:104] Can't declare the exchange: Exception (403) Reason: "ACCESS_REFUSED - operation not permitted on the default exchange"
> [E 161122 23:29:05 rabbitmq.go:104] Can't declare the exchange: Exception (504) Reason: "channel/connection is not open"
> [E 161122 23:29:05 rabbitmq.go:104] Can't declare the exchange: Exception (504) Reason: "channel/connection is not open"
> [E 161122 23:29:05 rabbitmq.go:104] Can't declare the exchange: Exception (504) Reason: "channel/connection is not open"
> ...

Since these exceptions are fired very fast (when the channel / connection can't be opened for whatever reason), I think some throttling mechanism should be implemented or have the client exit completely. What do you think?

### PR DESCRIPTION
**Pull request by mihaitodor**
- Fix #14
- Add a unit test for the erroneous behaviour
- Enable some tests that were left out by mistake in a previous commit
- Clean up environment variables that are set during tests in order to not interfere with other tests

### CODE REVIEW

File: sensu/config_test.go [hunk 1]
```diff
@@ -86,30 +81,53 @@ func validateClient(actualClient *stdClient.Client, t *testing.T) {
...
+			"Expected client subscriptions to be \"%#v\" but got \"%#v\" instead!",
 			expectedClient.Subscriptions,
 			actualClient.Subscriptions,
 		)
 	}
 }
 
-func expectedClientFromConfig(t *testing.T) {
-	config := Config{config: &configPayload{Client: expectedClient}}
+var dummyClient = &stdClient.Client{
```
Comment (AlexisMontagne) [inline sensu/config_test.go]: could you define this variable on top of the file right after the `package` block

**Review by AlexisMontagne — COMMENTED** [review]
Could you also replace the name of the arguments of the method `validateStringParameter`: `actualRabbitMqUri` and `expectedRabbitMqUri` are not really relevant anymore

File: sensu/config_test.go (hunk 1 above)
Comment (mihaitodor) [reply sensu/config_test.go]: Indeed, that's probably cleaner. Thanks!

**Comment by mihaitodor** [comment]
Thanks for spotting those 2 nonsensical variable names. They slipped by somehow after a refactor...

**Comment by AlexisMontagne** [comment]
LGTM
